### ISSUE TITLE
Dewpoint calculation

### ISSUE THREAD

**Issue by samweisgamdschie** [niesteszeck/idDHTLib#17]
Hi!

I need a source or reference where you have the formula of `double idDHTLib::getDewPointSlow()` from. According to the link in the comments the only function I consider to be relevant is `FUNCTION DWPT(T,RH)` but it looks way different to your approach. And the website of NOAA is like an information grave.I would be happy for any hint!

**Comment by niesteszeck** [comment]
Hi @samweisgamdschie.
This library is based on the original [DHTLib](https://playground.arduino.cc/Main/DHTLib/). The only work we made is a port of it to work with interrupts instead of delays, so the processor gets "free" while the communication with the sensors happens. We didn't modify the way to calculate things other that use of interrupts.

**Comment by samweisgamdschie** [comment]
OK, many thanks. I will ask them.
